set-option -g default-shell /bin/zsh
set-option -g default-command "zsh -l"
set-option -g update-environment "DISPLAY WAYLAND_DISPLAY XDG_RUNTIME_DIR"

set -s set-clipboard on

# vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# set vi-mode
set-window-option -g mode-keys vi

# vim visual mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# set true color
set -sa terminal-overrides ",xterm*:Tc"

# toggle status bar
bind -n M-b set-option -g status

# sesh setup
bind-key "T" run-shell "sesh connect \"$(
  sesh list | fzf-tmux -p 55%,60% \
    --no-sort --border-label ' sesh ' --prompt ' > ' \
    --header ' ^a all | ^t tmx | ^x zox | ^d kill ' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt( all > )+reload(sesh list)' \
    --bind 'ctrl-t:change-prompt( tmx > )+reload(sesh list -t)' \
    --bind 'ctrl-x:change-prompt( zox > )+reload(sesh list -z)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt( > )+reload(sesh list)' \
    --color 'bg:##030303,bg+:##4C4C4C,fg:##B8B8B8,fg+:##eeeeee,border:##4C4C4C,prompt:##D6D6D6,header:##888888,pointer:##eeeeee,label:##eeeeee'
)\""

# open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set-option -g status-position top
set -g status-left-length 100
set -g status-right-length 100

# terminal adjustments
set -a terminal-features ',xterm*:sixel'
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# mouse mode
# set -g mouse on
# unbind -n MouseDrag1Pane
# unbind -Tcopy-mode MouseDrag1Pane

set -g extended-keys on

# shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# shift alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# redimension panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "config reloaded"

# scratchpad terminal
bind -n M-g display-popup -d "#{pane_current_path}" -w 60% -h 60%

# cht.sh query
bind-key -r i run-shell "tmux neww ~/dotfiles/bin/cht.sh"

# set prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# plugin setup
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'jimeh/tmuxifier'
set -g @plugin 'christoomey/vim-tmux-navigator'

# tmux-resurrect & tmux-continuum
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'
set -g @continuum-boot 'on'

# theme setup
set -g @plugin 'erikw/tmux-powerline'
set -g status-style 'bg=default'
set -g window-status-style bg=default
set -g window-status-current-style bg=default

set-environment -g XDG_CONFIG_HOME "$HOME/.config"
run '~/.tmux/plugins/tpm/tpm'

set -g status-justify left
