hl.curve("minimal", { type = "bezier", points = { { 0.4, 0.0 }, { 0.2, 1.0 } } })
hl.animation({ leaf = "windows", enabled = true, speed = 2, bezier = "minimal", style = "popin 90%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2, bezier = "minimal", style = "popin 90%" })
hl.animation({ leaf = "fade", enabled = true, speed = 2, bezier = "minimal" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2, bezier = "minimal", style = "fade" })
hl.animation({ leaf = "layers", enabled = true, speed = 2, bezier = "minimal", style = "fade" })
