hl.curve("snappy", { type = "bezier", points = { { 0.1, 1 }, { 0.1, 1 } } })
hl.animation({ leaf = "global", enabled = true, speed = 1, bezier = "snappy" })
hl.animation({ leaf = "windows", enabled = true, speed = 1, bezier = "snappy", style = "popin 90%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1, bezier = "snappy", style = "popin 90%" })
hl.animation({ leaf = "fade", enabled = true, speed = 1, bezier = "snappy" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2, bezier = "snappy", style = "fade" })
hl.animation({ leaf = "layers", enabled = true, speed = 1, bezier = "snappy", style = "fade" })
