animations {
    enabled = yes
    bezier = snappy, 0.1, 1, 0.1, 1

    animation = windows, 1, 1, snappy, popin 90%
    animation = windowsOut, 1, 1, snappy, popin 90%
    animation = fade, 1, 1, snappy
    animation = workspaces, 1, 2, snappy, slide
    animation = layers, 1, 1, snappy, fade
}
