decoration {
    screen_shader =

    active_opacity = 0.8
    inactive_opacity = 0.6

    fullscreen_opacity = 1.0

    blur {
        enabled = true
        size = 10
        passes = 2
        new_optimizations = true
        ignore_opacity = true
        xray = true
        noise = 0.08
        contrast = 0.9
        brightness = 0.8
        vibrancy = 0.1696
        vibrancy_darkness = 0.0
    }

    shadow {
        enabled = false
    }
}
