general {
    gaps_in = 5
    gaps_out = 5
    border_size = 2
    
    col.active_border = rgba(e0e0e0ee) rgba(a0a0a0ee) 45deg
    col.inactive_border = rgba(333333aa)

    layout = dwindle
}

dwindle {
    preserve_split = yes
}

cursor {
    enable_hyprcursor = true
    sync_gsettings_theme = true
}

render {
    direct_scanout = false
}
