input {
    kb_layout = us, br
    kb_variant = , abnt2
    kb_model =
    kb_options = compose:ralt,lv3:ralt_alt
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = false
    }

    sensitivity = 0.5 # -1.0 - 1.0, 0 means no modification.
    force_no_accel = 0
    numlock_by_default = true
}

device {
	name = pnp0c50:0b-093a:0255-touchpad
	sensitivity = 0.75
}

device {
	name = pnp0c50:0b-093a:0255-mouse
	sensitivity = 0.5
}
