# Main modifier
$mainMod = SUPER

# other variables
$screenshot = ~/dotfiles/bin/screenshot.sh

# Applications
bind = $mainMod, Return, exec, kitty
bind = $mainMod CONTROL, Return, exec, hyprctl dispatch exec "[float;size 800 500;center] kitty"
bind = $mainMod, E, exec, kitty -e yazi
bind = $mainMod, Space, exec, rofi -show drun -config ~/.config/rofi/config.rasi
bind = $mainMod SHIFT, Escape, exec, kitty -e btop

# Power Menu
bind = $mainMod, Escape, exec, ~/.config/rofi/powermenu.sh

# Window management
bind = $mainMod, Q, killactive,
bind = $mainMod, F, fullscreen,
bind = $mainMod SHIFT, F, togglefloating,
bind = $mainMod SHIFT, P, pseudo,
bind = $mainMod, V, togglesplit,

# special workspace
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Focus movement (HJKL)
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Simple Resizing (Arrow keys)
binde = $mainMod, right, resizeactive, 20 0
binde = $mainMod, left, resizeactive, -20 0
binde = $mainMod, up, resizeactive, 0 -20
binde = $mainMod, down, resizeactive, 0 20

# Workspace switching
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# Move window to workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9

# Multimedia (Audio and Brightness)
bindle = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && ~/dotfiles/bin/volume-notify.sh
bindle = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && ~/dotfiles/bin/volume-notify.sh
bindl  = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && ~/dotfiles/bin/volume-notify.sh
bindle = , XF86MonBrightnessUp, exec, brightnessctl set 5%+ && ~/dotfiles/bin/brightness-notify.sh
bindle = , XF86MonBrightnessDown, exec, brightnessctl set 5%- && ~/dotfiles/bin/brightness-notify.sh

# screenshot
bind = $mainMod, P, exec, $screenshot sf

# Reload Hyprland Configuration
bind = $mainMod, M, exec, hyprctl reload && pkill waybar; waybar &

# open browser
bind = $mainMod, B, exec, zen-browser

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# keybind navigator
bind = $mainMod SHIFT, K, exec, ~/dotfiles/bin/keybinds.sh

# Toggle Waybar visibility
bind = $mainMod, W, exec, pkill waybar || waybar

# control center
bind = SUPER SHIFT, W, exec, kitty --class floating_shell -e ~/.config/hypr/scripts/control_center.sh
