exec-once = hyprctl setcursor NotwaitaBlack 24
exec-once = xrandr --output HDMI-A-1 --primary

# wallpaper setup
exec-once = swww-daemon
exec-once = swww init
exec-once = swww img /home/terminus/Pictures/dismvwpp.png --resize crop
# exec-once = mpvpaper -o "no-audio --loop-playlist" eDP-1 ~/Pictures/dismvwpp.mp4

# hypridle
exec-once = hypridle

# Status Bar (Waybar)
exec-once = waybar

# Notification Daemon (Dunst)
exec-once = dunst

# Authentication Agent
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Clipboard Management
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store

# Network & Bluetooth Applets (Optional but recommended)
exec-once = nm-applet --indicator
exec-once = blueman-applet

# Screen Brightness (For laptop use)
exec-once = brightnessctl set 10%
