windowrule = match:class ^(pavucontrol)$, float on
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(nm-connection-editor)$, float on

windowrule = match:class ^(Rofi)$, float on, center on

windowrule = match:class (floating_shell), float on, size 700 500, center on

layerrule = match:namespace rofi, blur on, ignore_alpha 0
layerrule = match:namespace waybar, blur on, ignore_alpha 0
layerrule = match:namespace dunst, blur on, ignore_alpha 0

windowrule = match:class ^(StarRail\.exe)$, suppress_event fullscreen, float on, size 1920 1080, center on
