# --- Window Rules ---
windowrule {
    name = floating_utilities
    match:class = ^(pavucontrol|blueman-manager|nm-connection-editor)$
    float = on
}

windowrule {
    name = rofi_centered
    match:class = ^(Rofi)$
    float = on
    center = on
}

windowrule {
    name = floating_shell_config
    match:class = ^(floating_shell)$
    float = on
    size = 800 600
    center = on
}

windowrule {
    name = yazi_picker_config
    match:class = ^(Yazi-Picker)$
    float = on
    size = 1000 600
    center = on
}

windowrule {
    name = speedcrunch_config
    match:class = ^(org\.speedcrunch\.speedcrunch)$
    float = on
    size = 700 500
    center = on
}

windowrule {
    name = kitty_opacity
    match:class = ^(kitty)$
    opacity = 1.0 0.6
}

windowrule {
    name = starrail_fullscreen
    match:class = ^(StarRail\.exe)$
    float = on
    size = 1920 1080
    center = on
}

# --- Layer Rules ---
layerrule {
    name = blur_rofi
    match:namespace = rofi
    blur = on
    ignore_alpha = 0.0
}

layerrule {
    name = blur_waybar
    match:namespace = waybar
    blur = on
    ignore_alpha = 0.0
}

layerrule {
    name = blur_dunst
    match:namespace = dunst
    blur = on
    ignore_alpha = 0.5
}
