[mgr]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
show_hidden = true
show_symlink = true

[preview]
tab_size = 2
max_width = 1000
max_height = 1000
image_delay = 30
wrap = "yes"

[opener]
display = [{ run = 'imv "$@"', detach = true, desc = "display image" }]
edit = [{ run = 'nvim "$@"', block = true, desc = "neovim" }]
pdf = [{ run = 'zathura "$@"', detach = true, desc = "zathura" }]
extract = [
  { run = 'ouch d -y "$@"', desc = "extract here with ouch", for = "unix" }
]
video = [{ run = 'mpv "$@"', detach = true, desc = "mpv" }]
office = [{ run = 'libreoffice "$@"', detach = true, desc = "libreoffice" }]

[open]
rules = [
  { url = "*.md", use = ["edit"] },
  { url = "*.{cpp,hpp,c,h}", use = ["edit"] },
  { url = "*.pdf", use = ["pdf"] },
  { mime = "text/*", use = ["edit"] },
  { mime = "inode/directory", use = ["edit"] },
  { mime = "image/*", use = ["display"] },
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive}", use = [
    "extract"
  ] },
  { mime = "application/vnd.oasis.opendocument.*", use = ["office"] },
  { mime = "application/vnd.openxmlformats-officedocument.*", use = ["office"] },
  { mime = "application/msword", use = ["office"] },
  { mime = "video/*", use = ["video"] },
]

[plugin]
prepend_previewers = [
  { mime = "inode/directory", run = "eza-preview" },
  { mime = "{audio,video}/*", run = "mediainfo" },
  { mime = "application/vnd.*", run = "office" },
  { mime = "text/*", run = "code" },
  { mime = "application/*zip", run = "ouch --archive-icon=''" },
  { mime = "application/x-tar", run = "ouch --archive-icon=''" },
  { mime = "application/bzip2", run = "ouch --archive-icon=''" },
  { mime = "application/gzip", run = "ouch --archive-icon=''" },
  { mime = "application/x-7z-compressed", run = "ouch --archive-icon=''" },
  { mime = "application/x-rar", run = "ouch --archive-icon=''" },
  { mime = "application/xz", run = "ouch --archive-icon=''" },
]
append_previewers = [
  { url = "*", run = "file-extra-metadata" },
]
append_spotters = [
  { url = "*", run = "file-extra-metadata" },
]
